sudo: false

language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "10"
  - "11"

os:
- linux

install:
  - travis_retry npm install

script:
  - uname -a
  - node --version
  - npm --version
  # linting
  - npm run lint
  # testing
  - npm run test
